site_name: Hackintosh How To Guides:Hackintosh.tools
site_url: https://hackintosh.tools
site_author: xuanyuan
site_description: "macOS Sonoma and OS X Ventura Hackintosh instructions, tutorials, step-by-step how to guides and installation videos; Hackintosh systems, parts and more."
repo_name: SeanChang/hackintosh
repo_url: https://github.com/SeanChang/hackintosh
copyright: Copyright &copy; 2022 - 2024 xuanyuan.me

theme:
  name: material
  icon:
      logo: material/apple
      repo: fontawesome/brands/git-alt
  favicon: https://xuanyuan.me/hackintosh/logo.webp
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - search.suggest
      - search.highlight
      - search.share
  palette:
    # Toggle light mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: dark mode
    # Toggle dark mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
extra:
  generator: false
  social:
    - icon: fontawesome/brands/redhat
      link: https://www.xuanyuan.me/blog
      name: xuanyuan.me
nav:
  - Introduction:
    - Background: "Introduction/Background.md"
    - Precautions: "Introduction/Precautions.md"
  - Basic:
    - Introduction: "Basic/Introduction.md"
    - Drivers: "Basic/Drivers.md"
    - Hardware: "Basic/Hardware.md"
    - Terminology: "Basic/Terminology.md"
  - USB Drive:
    - Download the image: "USB Drive/Download the image.md"
    - Write to the image: "USB Drive/Write to the image.md"
    - Structural Explanation: "USB Drive/Structural Explanation.md"
  - Preparation:
    - BIOS settings: "Preparation/BIOS settings.md"
    - Original file structure: "Preparation/OC file structure.md"
    - APCI&SSDT: "Preparation/APCI&SSDT.md"
    - Kext: "Preparation/Kext.md"
    - Drivers: "Preparation/Drivers.md"
    - OC editor: "Preparation/OC editor.md"
    - Preliminary configuration: "Preparation/Preliminary configuration.md"
    - Kexts fine - tuning: "Preparation/Kexts fine - tuning.md"
  - OC Config:
    - Quiks: "OC Config/Quiks.md"
    - UEFI: "OC Config/UEFI.md"
    - PCI: "OC Config/PCI.md"
    - Kernel: "OC Config/Kernel.md"
    - Misc: "OC Config/Misc.md"
    - NVRAM: "OC Config/NVRAM.md"
    - SMBIOS: "OC Config/SMBIOS.md"
    - config.list: "OC Config/config.list.md"
  - Demonstration:
    - Machine Overview: "Demonstration/Machine Overview.md"
    - BIOS: "Demonstration/BIOS.md"
    - Windows&macOS: "Demonstration/Windows&macOS.md"
    - WinNTSetup: "Demonstration/WinNTSetup.md"
    - Hackintosh: "Demonstration/Hackintosh.md"
    - Complete Success: "Demonstration/Complete Success.md"
  - High Customization:
    - USB customization: "High Customization/USB customization.md"
    - Compile the touchpad driver: "High Customization/Compile the touchpad driver.md"
    - Touchpad Interrupt Example: "High Customization/Touchpad Interrupt Example.md"
    - Dual - graphics - card display on a desktop computer: "High Customization/Dual - graphics - card display on a desktop computer.md"
    - Enable HiDPi: "High Customization/Enable HiDPi.md"
    - Troubleshooting Sleep Issues: "High Customization/Troubleshooting Sleep Issues.md"
    - Bluetooth in macOS 12: "High Customization/Bluetooth in macOS 12.md"
    - Mask the unsupported hard drives: "High Customization/Mask the unsupported hard drives.md"
    - AMD discrete graphics card optimization without driver installation: "High Customization/AMD discrete graphics card optimization without driver installation.md"
    - OC theme and boot entries: "High Customization/OC theme and boot entries.md"
    - Touch - screen Driver under macOS: "High Customization/Touch - screen Driver under macOS.md"
    - Customize the monitor icon: "High Customization/Customize the monitor icon.md"
    - Customization of Integrated Graphics Interface Output: "High Customization/Customization of Integrated Graphics Interface Output.md"
  - Perfect Hackintosh:
    - Hackintosh: "Perfect Hackintosh/Hackintosh.md"
    - Genuine Mac: "Perfect Hackintosh/Genuine Mac.md"
  - OC Error Troubleshooting:
    - Abnormal Log: "OC Error Troubleshooting/Abnormal Log.md"
    - Normal Log: "OC Error Troubleshooting/Normal Log.md"
  - FAQ:
    - Usage method: "FAQ/Usage method.md"
    - Question list: "FAQ/Question list.md"